### ISSUE TITLE
Inject PhoneNumberValidator as service

### ISSUE THREAD

**Issue by ekut** [odolbeau/phone-number-bundle#33]
I need to inject PhoneNumberValidator into my custom validator (or into my other own services). Like I can do with Symfony `EmailValidator`:

```
// services.yaml

App\Validator\Constraints\MyOwnService:
        arguments: ['@validator.email']
```

Can I do some trick with PhoneNumberValidator? Or we need to do some changes in the bundle first?

**Comment by odolbeau** [comment]
Hi @ekut 
The bundle doesn't declare the validator as a service but you can do it by yourself with something like this (not tested):

```yaml
Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumberValidator:
  tags: [validator.constraint_validator]

App\Validator\Constraints\MyOwnService:
        arguments: ['@Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumberValidator']
```

Tell me if it solves your problem!
